### ISSUE TITLE
BoardRelations Schema Issue

### ISSUE THREAD

**Issue by jtprichard** [DireWolfZA/MondayApiClient#1]
I appreciate your making this public - it is extremely useful, especially for an amateur programmer.
I am having an issue with the board relations mutation, which I have tracked down to the Monday api requriing a query that looks for "item_ids" as opposed to "linked_item_ids".  
"{\"connect_boards__1\" : {\"item_ids\" : [\"9999999999\", \"9999999999\"]}
This has tested out in the API playground, as well as sending the query directly.  I attempted to change your Schema, but quickly found that the Monday Api query is still returning "linked_item_ids".  
Are you aware of the issue, and do you have an idea for a simple fix?

**Comment by Walkman100** [comment]
Hi @jtprichard,
Awesome that someone else has actually found this useful. Feels like there are no .Net devs working on the Monday API.

I'm guessing you're trying to change a column, and creating a new BoardRelationValue to do so - it looks like I already came across this issue:
https://github.com/DireWolfZA/MondayApiClient/blob/b6695de21ba1637704d5d1b3a7fa12fc6e18be05/MondayApi/Schema/Models/ColumnValues/BoardRelationValue.cs#L23-L27

All you need to do is create a `BoardRelationValueForUpdate` and use `ItemIDs` instead!

I guess the lack of documentation here is to blame. I'd like to have everything documented, but the Monday API is so expansive that I don't even know where to start.

**Comment by Walkman100** [comment]
Actually this was fixed in https://github.com/DireWolfZA/MondayApiClient/commit/a28e76cc707ff5e41f1c09d0faac9d135d3d9db9 but 🤷

**Comment by jtprichard** [comment]
Great!  I'll check it out.  
My fix was to update your MondayApiClient.cs to include the ability to provide my own query.  I used your query builder for ease, and then modified the query string to fix the issues I was having, then pushed it through a new Run method that took the query.  

        public Task<Query> RunQuery(string query) => Run<Query>(query);
        public Task<Mutation> RunMutation(string query) => Run<Mutation>(query);

        public async Task<T> Run<T>(string query)
        {
                [code from your Run<T> method]}
        }

You might think about adding a way to serialize a custom query provided by the user.  If anything, it can be helpful for testing / debugging.

I do appreciate your making this available - it has been very useful.
